### ISSUE TITLE
tests are failing on Node 0.10

### ISSUE THREAD

**Issue by nathanhleung** [nathanhleung/install-peerdeps#26]
need to get tests working on 0.10

**Comment by nathanhleung** [comment]
Fixed by #28

**Comment by ljharb** [comment]
Not actually fixed; just allowed to fail.

The only solution is switching from jest to tape, since tape is the only remaining test runner that works on older nodes. (This should be reopened)

**Comment by ljharb** [comment]
Happy to send a PR switching to tape if you’re willing to accept it!

**Comment by nathanhleung** [comment]
That would be wonderful! I was looking at some other test runners (Mocha etc) but all of them have stopped supporting Node <4. Is Tape used at Airbnb?

**Comment by ljharb** [comment]
We use it for some of our public packages, and will be likely migrating all of them (that support older nodes) to it.
